### PR TITLE
Props

### PR DESCRIPTION
**Pull request by 02agarwalt**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/keras-rl/1)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 1 of 3 files at r1, 1 of 3 files at r3.
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[sync.sh, line 3 at r3](https://reviewable.io:443/reviews/jhu-asco/keras-rl/1#-KzgB08WYGR4okW8cSDu:-KzgB08X0x1F-T__vD0P:bo02s1q) ([raw file](https://github.com/jhu-asco/keras-rl/blob/8ae14ac19ea932f10bb222f3867e6282ca3b21e7/sync.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> sudo cp $1 /usr/local/lib/python2.7/dist-packages/$1
> ```

What are you using this for?   Is there a reason you need to copy files to /usr/local?

---

*[examples/cem_props_cartpole.py, line 56 at r3](https://reviewable.io:443/reviews/jhu-asco/keras-rl/1#-KzgBJQin6-rcS5E2aup:-KzgBJQin6-rcS5E2auq:b-3mgerb) ([raw file](https://github.com/jhu-asco/keras-rl/blob/8ae14ac19ea932f10bb222f3867e6282ca3b21e7/examples/cem_props_cartpole.py#L56)):*
> ```Python
>     cem.compile()
>     callback_cem = cem.fit(env, nb_steps=steps_cem, visualize=False, verbose=0)
>     #cem.save_weights('cem_dumps/cem_{}_{}_ti_{}_bs_{}_steps_{}.h5f'.format(ENV_NAME, model_type, train_interval_cem, batch_size_cem, steps_cem), overwrite=True)
> ```

You can remove commented code if it is unused.  Looks like we want to  be saving weights and plots, so maybe just uncomment that stuff.

---

*[rl/agents/props_util.py, line 387 at r3](https://reviewable.io:443/reviews/jhu-asco/keras-rl/1#-KzgCOJx3PUtLX0jR5cd:-KzgCOJx3PUtLX0jR5ce:b-6g28m3) ([raw file](https://github.com/jhu-asco/keras-rl/blob/8ae14ac19ea932f10bb222f3867e6282ca3b21e7/rl/agents/props_util.py#L387)):*
> ```Python
>         #dwdms = dpdms / p0s[:, :, np.newaxis]
>         dwdms = np.sign(dpdms) * np.exp(np.log(np.abs(dpdms)) - log_p0s[:, :, np.newaxis])
>         dwdSs = np.sign(dpdSs) * np.exp(np.log(np.abs(dpdSs)) - log_p0s[:, :, np.newaxis])
> ```

make sure you merge up your branch with master.  I added some things and it looks like they got deleted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/keras-rl/1)*

**Comment by msheckells** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/keras-rl/1)*

**Comment by 02agarwalt** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[sync.sh, line 3 at r3](https://reviewable.io:443/reviews/jhu-asco/keras-rl/1#-KzgB08WYGR4okW8cSDu:-Kzkz6Ud-RYtkfNDs-gW:b8o5ko4) ([raw file](https://github.com/jhu-asco/keras-rl/blob/8ae14ac19ea932f10bb222f3867e6282ca3b21e7/sync.sh#L3)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

What are you using this for?   Is there a reason you need to copy files to /usr/local?
</blockquote></details>

I already have keras-rl pip installed on my machine, so I'm unable to use the jhu-asco/keras-rl fork. For example, the line "from rl.agents.props import PROPSAgent" doesn't work because it automatically uses the original installed version of keras-rl. So I'm using this file to copy all my changes to the folder of the installed package.

There is probably a better way but I'm unaware of it. How are you able to use the fork?

---

*[examples/cem_props_cartpole.py, line 56 at r3](https://reviewable.io:443/reviews/jhu-asco/keras-rl/1#-KzgBJQin6-rcS5E2aup:-Kzl-eeoUHD__eVoczUj:b-896fix) ([raw file](https://github.com/jhu-asco/keras-rl/blob/8ae14ac19ea932f10bb222f3867e6282ca3b21e7/examples/cem_props_cartpole.py#L56)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

You can remove commented code if it is unused.  Looks like we want to  be saving weights and plots, so maybe just uncomment that stuff.
</blockquote></details>

Done.

---

*[rl/agents/props_util.py, line 387 at r3](https://reviewable.io:443/reviews/jhu-asco/keras-rl/1#-KzgCOJx3PUtLX0jR5cd:-Kzl-cJj4YWJt2A7KPqF:b-896fix) ([raw file](https://github.com/jhu-asco/keras-rl/blob/8ae14ac19ea932f10bb222f3867e6282ca3b21e7/rl/agents/props_util.py#L387)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

make sure you merge up your branch with master.  I added some things and it looks like they got deleted
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/keras-rl/1)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sync.sh, line 3 at r3](https://reviewable.io:443/reviews/jhu-asco/keras-rl/1#-KzgB08WYGR4okW8cSDu:-KzqYqD-hjPhtQ6NM8As:b-9nyq3a) ([raw file](https://github.com/jhu-asco/keras-rl/blob/8ae14ac19ea932f10bb222f3867e6282ca3b21e7/sync.sh#L3)):*
<details><summary><i>Previously, 02agarwalt (Tanay Agarwal) wrote…</i></summary><blockquote>

I already have keras-rl pip installed on my machine, so I'm unable to use the jhu-asco/keras-rl fork. For example, the line "from rl.agents.props import PROPSAgent" doesn't work because it automatically uses the original installed version of keras-rl. So I'm using this file to copy all my changes to the folder of the installed package.

There is probably a better way but I'm unaware of it. How are you able to use the fork?
</blockquote></details>

If you don't need to keep that version around, you can probably just overwrite that installation with this fork using `pip install -e`, where -e makes it so changes you make to source are reflected in the system install.  

---

*[rl/agents/props_util.py, line 1 at r6](https://reviewable.io:443/reviews/jhu-asco/keras-rl/1#-KzqZptW3lBOQlF8_NT4:-KzqZptW3lBOQlF8_NT5:b90eqt0) ([raw file](https://github.com/jhu-asco/keras-rl/blob/100db87ea5cad7de85dddd21c9c46bf8129eb8e0/rl/agents/props_util.py#L1)):*
> ```Python
> import autograd.numpy as np
> ```

I also removed this in a commit, but it looks like it got put back.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/keras-rl/1)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/keras-rl/1)*

**Pull request merged**
